# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Info',
            fields=[
                ('Project_Name', models.CharField(help_text='Project Name', max_length=30)),
                ('Project_Short_Name', models.CharField(help_text='Project Short Name', max_length=10, primary_key=True, serialize=False)),
                ('Project_Manager', models.CharField(help_text='Project Manager Name', max_length=30)),
                ('Project_Architect', models.CharField(help_text='Project Architect Name', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Stream_Table',
            fields=[
                ('Project_Short_Name', models.CharField(help_text='Project Short Name', max_length=10, primary_key=True, serialize=False)),
                ('Project_Stream', models.CharField(help_text='Stream Name', max_length=10)),
                ('Project_Release_Label', models.CharField(help_text='Release Label', max_length=10)),
                ('Project_Release_Label_Date', models.DateField(help_text='Released Date')),
                ('Project_Release_Label_inprogress', models.CharField(help_text='Draft Release Label', max_length=10)),
                ('Project_Release_Label_Date_inprogress', models.DateField(help_text='Draft Release Date')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='project_stream_table',
            unique_together=set([('Project_Short_Name', 'Project_Stream')]),
        ),
    ]
