# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160831_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_stream_table',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_stream_table',
            name='Project_Short_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Project_Info'),
        ),
    ]
