# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20160831_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_stream_table',
            name='Project_Release_Label_Date',
            field=models.DateField(blank=True, help_text='Released Date', null=True),
        ),
        migrations.AlterField(
            model_name='project_stream_table',
            name='Project_Release_Label_Date_inprogress',
            field=models.DateField(blank=True, help_text='Draft Release Date', null=True),
        ),
        migrations.AlterField(
            model_name='project_stream_table',
            name='Project_Release_Label_inprogress',
            field=models.CharField(blank=True, help_text='Draft Release Label', max_length=10, null=True),
        ),
    ]
