# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20160831_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRQtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRQid', models.CharField(help_text='CRQ Id', max_length=10)),
                ('StreamName', models.CharField(help_text='Stream Name', max_length=10)),
                ('Architect_BAName', models.CharField(blank=True, help_text='Architect Name', max_length=50, null=True)),
                ('Req_DesStartDate', models.DateField(blank=True, help_text='Requirement/Design Start Date', null=True)),
                ('Req_DesCompletionDate', models.DateField(blank=True, help_text='Requirement/Design Completion Date', null=True)),
                ('FRS_link', models.URLField(blank=True, null=True)),
                ('DeveloperName', models.CharField(blank=True, help_text='Developer Name', max_length=50, null=True)),
                ('DevStartDate', models.DateField(blank=True, help_text='Development Start Date', null=True)),
                ('DevCompletionDate', models.DateField(blank=True, help_text='Development Completion Date', null=True)),
                ('ObjectPackagelink', models.URLField(blank=True, null=True)),
                ('ReleaseNotelink', models.URLField(blank=True, null=True)),
                ('TesterName', models.CharField(blank=True, help_text='Tester Name', max_length=50, null=True)),
                ('TestStartDate', models.DateField(blank=True, help_text='Test Start Date', null=True)),
                ('TestCompletionDate', models.DateField(blank=True, help_text='Test Completion Date', null=True)),
                ('TestCaselink', models.URLField(blank=True, null=True)),
                ('TestResultlink', models.URLField(blank=True, null=True)),
                ('LastModifieddate', models.DateField(auto_now_add=True, help_text='Last Modification Date')),
                ('Project_stream_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Project_Stream_Table')),
            ],
        ),
    ]
