# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_crqtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crqtable',
            old_name='StreamName',
            new_name='Project_Stream',
        ),
        migrations.RemoveField(
            model_name='crqtable',
            name='Project_stream_Name',
        ),
        migrations.AddField(
            model_name='crqtable',
            name='Project_Short_Name',
            field=models.ForeignKey(default='ATBF', on_delete=django.db.models.deletion.CASCADE, to='tracker.Project_Info'),
            preserve_default=False,
        ),
    ]
