# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20160831_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Releasetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReleaseId', models.CharField(help_text='Release Number', max_length=10)),
                ('Project_Stream', models.CharField(help_text='Stream Name', max_length=10)),
                ('InitiationDate', models.DateField(auto_now_add=True, help_text='Initiation Date')),
                ('CompletionDate', models.DateField(help_text='Completion Date')),
                ('LastModifieddate', models.DateField(auto_now_add=True, help_text='Last Modification Date')),
                ('FRS_link', models.URLField(blank=True, null=True)),
                ('SVN_link', models.URLField(blank=True, null=True)),
                ('Linked_CRQid', models.CharField(help_text='CRQ Id', max_length=100)),
                ('Initiator_User', models.CharField(blank=True, help_text='Initiator', max_length=50, null=True)),
                ('Initiator_Timeline', models.DateField(blank=True, help_text='Initiation Completed Date', null=True)),
                ('Manager_User', models.CharField(blank=True, help_text='Release Manager', max_length=50, null=True)),
                ('Manager_timeline', models.DateField(blank=True, help_text='Release Manager Review Completed Date', null=True)),
                ('Approver_User', models.CharField(blank=True, help_text='Release Approver', max_length=50, null=True)),
                ('Approver_timeline', models.DateField(blank=True, help_text='Release Approval Date', null=True)),
                ('Project_Short_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Project_Info')),
            ],
        ),
    ]
