# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_releasetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_stream_table',
            name='Project_Stream',
            field=models.CharField(default='010000', help_text='Stream Name', max_length=10),
        ),
    ]
