# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20160903_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_stream_table',
            name='Project_Release_Label',
            field=models.CharField(help_text='Release Label', max_length=10),
        ),
    ]
